### ISSUE TITLE
[API] NginxとPHP周りの設定の見直し

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/Stocklist#110]
## アップロードした画像が見えない
アップロードした画像を参照しようとすると強制的にVue.jsの方が表示されてしまって画像が表示されない。
(原因としてapiとVue.jsのみに割り振るようにしているため)
php artisan storage:linkした画像を表示できるようにして欲しいです。
仕組みとしてはphp artisan storage:link周りの仕様を参照
https://readouble.com/laravel/7.x/ja/filesystem.html

## 大きいサイズの画像がアップロードできない
デフォルトのファイルサイズが小さいのでファイルサイズを
最大アップロードサイズを100Mぐらいにして欲しいです

**Comment by yumekiti** [comment]
変更しておきました。
