### ISSUE TITLE
Home取得APIの実装

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/Stocklist#7]
## 説明
自分が所属するHomeを取得するためのエンドポイント。

## エンドポイント
``` GET /api/homes  ```

## 認証
認証が必要です。

## Query Parameter
なし

## Request Body
なし

## Response Body
```
{
    ...Home,
    members: [
        ...User
    ]
}
```

## Controller
Api/HomeController@show
## FormRequest

FormRequest名: FormRequestのクラス名
なし

**Comment by yumekiti** [comment]
https://github.com/Kinoshita0623/Stocklist/tree/feature/%237%2FHomeApi

**Comment by Kinoshita0623** [comment]
設計を見直しました。
