### ISSUE TITLE
[API]Box作成API

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/Stocklist#74]
## 説明
収納場所（Box）を作成します。

## エンドポイント
``` POST  /api/boxes ```

## 認証
認証が必要です。

## Query Parameter
なし

## Request Body
|key|type|required|説明|
|-|-|-|-|
|name|text|yes|収納の名称
|description|text|no|収納の説明

## Response Body
作成したBoxを返します。
関連オブジェクトをネストさせる必要はありません。
またwithCountまたはloadCountを使ってstocksの個数を含めるようにしてください。
```
// インスタンス化済みであれば
$box->loadCount('stocks')

// QueryBuilderであれば
$boxQuery->withCount('stocks')
```

## Controller
Api/BoxController@create(CreateBoxRequest $box)

## FormRequest

FormRequest名: CreateBoxRequest
|key|条件|
|-|-|
|name|required, max:20|
|description|max:255|

**Comment by yumekiti** [comment]
https://github.com/Kinoshita0623/Stocklist/tree/feature/%2374%2FCreateBoxApi

withCountまたはloadCountを使ってstocksの個数を含めるようにしてください。
どうやっってふくむのおおおおお；；

**Comment by yumekiti** [comment]
以下のように表示された。
```
{
    "name": "test-item",
    "description": "testtest",
    "home_id": 1,
    "updated_at": "2021-05-27 07:04:50",
    "created_at": "2021-05-27 07:04:50",
    "id": 78,
    "stocks_count": 0
}
```
