### ISSUE TITLE
[API]買い物リストのモデル、マイグレーション作成

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/Stocklist#78]
## 買い物リスト(ShoppingList)
|key|type|説明|
|-|-|-|
|id|ulong primary key autoincrement|主キーサロゲートキー
|title|text|買い物リストのタイトル|
|user_id|ulong(nullable)|usersのprimary keyを参照する外部キー|
|home_id|ulong|homesの種キーを参照する外部キー|

### Modelのfillable
* title
* user_id
* home_id

## 買い物詳細(ShoppingDetail)
|key|type|説明|
|-|-|-|
|item_id|ulong|アイテムの主キーの参照キー|
|count|int|購入する個数|
|box_id|ulong(nullable)|補充する予定の収納先(Box)の参照キー|
|completed_at|date(nullable)|完了した日時|
|shopping_list_id|ulong|shopping_listsの主キーを参照する外部キー|

### Modelのfillable
* item_id
* count
* completed_at
* shopping_list_id
* stock_id
## 備考
* box_idのon deleteはset nullにする。
* shopping_list_idのon delete制約はcascadeにする。
* home_idのon delete制約はcascadeにする。

**Comment by Kinoshita0623** [comment]
## 仕様修正箇所
* home_idを追加した。
* fillableについての説明を追加した
* ShoppingDetailにshopping_list_idにShoppingListを参照する外部キーを追加した
* 削除制約などについて

**Comment by hanezumi** [comment]
完成
