### ISSUE TITLE
[API]Stockの変更履歴を記録するようにする。

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/Stocklist#92]
StockHistoryモデル
stock_historiesモデルを作成する。  
stocksのcountの変更とイベント発生時のtimestampを記録するようにする。
主キーは連番にする。  
外部キー制約は持たせるが、削除時の制約はSET NULLにする。

**Comment by Kinoshita0623** [comment]
#　テーブルの情報
table名: stock_histories
カラム
- id(bigIncrements)
- stock_id(unsignedBigInteger) references stocks(id)
- item_id(unsignedBigInteger) references items(id)
- box_id(unsignedBigInteger) references box(id)
- count(integer)
- timestamp

stock_id, item_id, box_idは参照制約をつける
delete on set nullにする。

**Comment by hanezumi** [comment]
完成しました
